### ISSUE TITLE
Space in aside.md link

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-ping-kong#10]
In https://github.com/mozilla/mozilla-club-activity-ping-kong/blob/8215c5b2d8bf3bed3e4f87727165597d6539ae22/activity-data/content/en/aside.md there is a space between the square bracket and the round ones pointing to the sign resource. Some Markdown interpreters may get confused here.

**Comment by soapdog** [comment]
Yep, that was fixed while I was fixed the alt-text. Thanks for pointing that out.
