### ISSUE TITLE
Localization of aside.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-ping-kong#11]
#### दर्शक
- ८ +
-  प्रणाली विचारकों से शुरुआत
#### सामग्री
- मुद्रित [बाधा कोर्स लक्षण](http://www.mousesquad.org/files/u4/pingkongcards.png)
- वेब ब्राउज़र ( इच्छानुसार)
#### सीखने का  मकसद
- खोज शब्दों के बीच फर्क , यूआरएल और आईपी के पते
- दो कंप्यूटरों के बीच सूचना के प्रवाह का पालन करें
- वेब और इंटरनेट के बीच व्यावहारिक मतभेद का वर्णन करें 
- ओपन  वेब पर उपकरण का उपयोग करके  सर्वर के भौतिक अड्रेस का  पता लगाएँ।
#### कैसे  विद्यार्थी विश्वसनीय सलाहकार बने ?
- एक छात्र या कम अनुभवी सहज बनाने वाले  पे अपनी  प्रतिछाया रखें जिससे की वो भी इस गतिविधि का प्रमुख अभ्यास कर सकते हैं !
- अगर कुछ छात्र तेजी से बढ़ रहे हैं  या गतिविधि में अधिक विश्वास कर रहे हैं, तो उन्हें दूसरे समूह के संरक्षक सहकर्मी के लिए कहें।
- छात्रों को उत्साहित करके गतिविधि को समाप्त करें ताकि वो अपने दोस्तों और परिवार जनक को भी यह पढ़ाएं !
#### समुदाय रीमिक्स देखें

शिक्षकों और कार्यकर्ताओं में उनके विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है तरीकों की जाँच करें हमारे [ वाद-विवाद सभा में ](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Thanks a lot for the awesome work!!!! :smile_cat: it is available at http://mozilla.github.io/mozilla-club-activity-ping-kong/#hi

**Comment by join2ashish** [comment]
Thank You :)
