### ISSUE TITLE
Localization of activity.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-ping-kong#12]
---

शीर्षक: पिंग काँग
गिटहब : मोज़िला/मोज़िला-सभा-गतिविधि--पिंग-काँग
तस्वीर: पिंगकाँग.पीएनजी
दक्षताओं:
    - {लेबल: "वेब यांत्रिकी", प्रकार: "वेब यांत्रिकी"}
### पिंग काँग

 द्वारा निर्मित [माउस](http://mouse.org/) फोटो सहित, चाड सेंसिंग ,  द्वारा क्लब के लिए रिमिक्स [मोज़िला](https://webmaker.org/mentor).

कई लोगों के लिए , "इंटरनेट" एक सार और भारी अवधारणा है. यह गतिविधि विद्यार्थीयों को चुनैति देती है की वें इससे वस्तुतः रूप में सोचें की इंटरनेट एक कंप्यूटर के साथ कैसे संचार करे !.**

१ - २ घंटा 
### तैयारी

**पूरा कीजिये** [पूर्व गतिविधि प्रश्नावली](http://goo.gl/forms/Uua6yKIy5E).

इसके बाद *\* गतिविधि अपने आप करें *\* उसके साथ परिचित होने के लिए !

*\* निम्नलिखित के साथ *\* खुद परिचित कराएं  [शर्तों](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. कमांड लाइन / कमान प्रोम्प्ट 
2. हॉप 
3. इंटरनेट प्रोटोकॉल ( आईपी) एड्रेस 
4. इंटरनेट सेवा प्रदाता ( आईएसपी)
5. वेब सर्वर
6. लोकल एरिया नेटवर्क (लैन)
7. पैकेट  
8. पिंग 
9. राऊटर 
10. ट्रेसरूट

*मुद्रण और इसको बहार निकले  [ पिंग काँग बाधा कोर्स के संकेत](http://www.mousesquad.org/files/u4/pingkongcards.png).

बाधा कोर्स के लिए अपने कमरे में पर्याप्त जगह साफ़ करें ."  कमरे के विपरीत दिशा में "मेरा कंप्यूटर" और "वेबसाइट " लेबल करके  कार्ड को टांग दें।

! [ पिंग काँग कार्ड](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

१ ० <बी आर >मिनट 
### परिचय

शिक्षार्थियों से पूछो, \* "कैसे आपको  इंटरनेट मिलता है? " *

 अपने समूह से राय लें और उसके बाद निम्नलिखित समझाएं :

![इंटरनेट ग्राफिक](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)

> "इंटरनेट" नेटवर्क की एक प्रणाली और "वेब" इंटरनेट के शीर्ष पर बैठता है और दुनिया भर के विभिन्न कंप्यूटर में संग्रहित जानकारी के साथ देखने और बातचीत के लिए एक इंटरफेस प्रदान करता है. स्किल क्रश के इस छोटे से लेख, आगे इंटरनेट और वेब के बीच का अंतर बताते हैं।

इसके अलावा समझायें की :

> कभी भी आप कुछ करने के लिए इंटरनेट से  पूछते हैं , फिर चाहे वेब ब्राउज़र में यूआरएल डालना हो या यूट्यूब पे वीडियो देखनी हो , आपकी इंटरनेट अनुरोध "हॉप " के माध्यम से कई नेटवर्क उपकरणों जैसे रूटर्स , स्वित्चेस और सर्वर्स से अपने रस्ते पर जाता है आपके कंप्यूटर से वेब सर्वर पर.

बाधा कोर्स शुरू करने से पहले शिक्षार्थियों एक छोटे से अधिक संदर्भ देने के लिए परिचयात्मक वीडियो देखें:
#### वहाँ और वापस फिर से: एक पैकेट की कथा

[![वहाँ और वापस फिर से: एक पैकेट की कथा](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

१ ५ <बी आर >मिनट  
### नेट का प्रदर्शन करना

एक छोटे ४ - ५  अभिनेताओं का सुधार समूह बनाये . एक साथ हो जाएं और मंथन करके एक प्रदर्शन का रास्ता निकले की इंटरनेट कैसे काम करता हैं !. अपने जगह को कैसे इस्तेमाल करना है उसके बारे में सोचें  - आप कहीं भी प्रदर्शन कर सकते है वहां पर आपके चारो ओर उस जगह पे एक कमरा है और उससे बहार निकल के चारों ओर स्थानांतरित कर सकते हैं. आप के आसपास सामग्री के बारे में सोचें और उससे उठा लें जो काम में नेट दिखाने में मदद कर सकता है !.

एक दूसरे के लिए अपने नाटक का प्रदर्शन करें . अन्य समूहों के लिए अपने दिल बाहर सराहना दें . नेट इतिहास प्रदर्शन के लिए विशेष रूप से महान क्षण पर हसें  हैं और खुश हो जाएं !

---

५ <बी आर >मिनट 
### बाधा कोर्स का सेट अप करें

इस रास्ते को समझने में मदद करने के लिए कहें , हम एक बाधा कोर्स में *\* अधिनियम बाहर एक मानव पिंग / ट्रेसरूट के लिए जा रहे हैं.**

हम यहाँ से यात्रा करेंगे i) स्थानीय कंप्यूटर के माध्यम से ii) एक लेन से  iii) इंटरनेट से प्राप्त करने के लिए iv) Google.com या अपनी पसंद की वेबसाइट.

![बाधा कोर्स की एक तस्वीर](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

अपने समूह से पूछे की  "मेरा कंप्यूटर" पर हस्ताक्षर के नीचे इकट्ठा हों  और  तीन स्वयंसेवकों से पूछें .**

संकेत लेबल स्वयंसेवकों के हाथ तीन *_"हॉप १ : लोकल रूटर ", "हॉप २ : इंटरनेट सर्विस प्रोवाइडर एंड "हॉप ३ : दी वेबसाइट कंपनी रूटर " *_ और कमरे में बाहर का फ़ैल जाने के प्रसार करने के लिए उन्हें पूछें ।

बताएं **संकेत विभिन्न "हॉप्स का प्रतिनिधित्व"** जो की एक उपयोगकर्ता के लिए लग रही वेबसाइट में पहुँचने से पहले एक इंटरनेट अनुरोध के माध्यम से जाना चाहिए. बाकि बचे हुए छात्र जो कंप्यूटर कोड के पैकेट्स है और कोशिश कर रहे हैं वेबसाइट के दूसरे कमरे में जाने के लिए .

![फैसिलिटेटर की एक तस्वीर जो संकेतों को समझा रहा है ](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

१ ० <बी आर >मिनट 
### बाधा कोर्स का मॉडल

*_वे सभी गतिविधि शुरू करने से पहले समूह के आराम के लिए *_ एक मॉडल के रूप में कार्य करने के लिए इन "पैकेट " छात्रों में से एक चुनें.

शिक्षार्थियों इस परिदृश्य दें

> मैं अपने कंप्यूटर पर हूँ और मैं यूट्यूब पर एक वीडियो देखने के लिए तय किया हैं . उसके बाद मैं वेब पते में टाइप किया  , मेरे कंप्यूटर ने 'youtube.com' कोड में धर्मान्तरित किया जो सरे कंप्यूटर पढ़ सकते हैं  और उसके बाद उससे भिन इंटरनेट "पैकेट्स" में विभाजित कर दिया . यह स्वयंसेवक छात्र उन पैकेट में से एक का प्रतिनिधित्व करता है !

![कार्रवाई में गतिविधि और एक स्थानीय रूटर के रूप में खेल रहे एक व्यक्ति दिखा की तस्वीर](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### हॉप १ : लोकल रूटर

एक उदाहरण के लिए छात्र से चलने के लिए पूछे की  "हॉप १ : लोकल रूटर " और उससे समझाएं :

> पहला पैकेट रूटर्स की तरह स्थानीय नेटवर्क उपकरणों के माध्यम से हॉप जाएगा , स्विच या अपने भवन में मोडेम के द्वारा . स्थानीय नेटवर्क उपकरणों को इंटरनेट से पैकेट भेज देते हैं।
#### हॉप २ : इंटरनेट सर्विस प्रोवाइडर

चलने के लिए छात्रों को लें और अगला हॉप समझाएं :

> एक पैकेट यहाँ आ जाने के बाद, इंटरनेट सेवा प्रदाता के लिए, यह यूट्यूब के routers में से एक के लिए सभी तरह से भेजा जाता है.
#### हॉप ३ : कंपनी रूटर

> जब पैकेट YouTube के रूटर के माध्यम से जाता है, तो यह मेरे वीडियो धारा होने कि कंपनी के मुख्यालय में एक कंप्यूटर के लिए भेजा जाता है.
#### वेबसाइट

> आदेश में अपने कंप्यूटर पर स्ट्रीम करने के लिए वीडियो पाने के लिए, यूट्यूब के कंप्यूटर भी पैकेट में मेरे वीडियो धर्मान्तरित करते हैं , जो नेटवर्क उपकरणों को  एक ही रास्ते पर अपने कंप्यूटर को वापस सभी तरह से यात्रा करके यह यूट्यूब को पाने के लिए ले लिया गया .

**आप को वापस चलने के लिए उदाहरण के छात्र से पूछो,** रास्ते पर प्रत्येक हॉप पर वापस थामने के लिए सुनिश्चित करें .
#### आईपी एड्रेस

जब छात्र वापस आएंगे , दूसरों से पूछें की कैसे हर हॉप पर उपकरणों को ठीक से पता चलता है की कहाँ पैकेट्स भेजने हैं . अगर कोई नहीं जानता है, तो उन्हें समझाएं :

> वे ई पी एड्रेस का उपयोग करते हैं  ! ऑनलाइन एक नेटवर्क में या हर डिवाइस या कंप्यूटर का एक आईपी ( " इंटरनेट प्रोटोकॉल ") होता है . यह एक घर के पते की तरह है - और यह डिवाइस एक दूसरे को खोजने और संवाद में मदद करता है. आईपी ​​पते इस तरह एक स्ट्रिंग में संख्या के 4 सेट होते है जैसे : 172.168.3.12
#### हॉप्स के बीच में

बाधा कोर्स को और अधिक दिलचस्प बनाने के लिए, आप हॉप्स के बीच "सरकार जासूस" जगह हो सकता है. [EFF से यह संसाधन है ](https://www.eff.org/pages/tor-and-https) हॉप्स के बीच डेटा को रोकना कैसे हो सकता है यह तीसरे पक्षों बताते हैं. कौन सा डेटा कमजोर क्या है, और कौन सा डेटा सुरक्षित है के बारे में अपने शिक्षार्थियों के साथ बात करें।

---

१ ५ <बी  आर >मिनट 
### दौड़ के लिए रवाना!

अब यह हर किसी बाधा कोर्स की कोशिश करने के लिए समय है!

**छात्रों को समझाओ की वे सभी " पैकेट " हैं  और गूगल.कॉम तक जाने का प्रयास कर रहे है  (या वेबसाइट जो आप  चुने ) किसी के इंटरनेट अनुरोध को पूरा करने के लिए. उन्हें अगले एक पर जाने से पहले प्रत्येक " हॉप" पर रोकना होगा.

**लेकिन वहाँ एक मोड़ है , इंतजार करें !** इससे पहले पैकेट अगले करने के लिए एक हॉप से प्राप्त कर सकते हैं , उन्हें ये शीघ्र ही पूरा करना होगा हॉप के रूप में अभिनय के छात्र की चुनौती. _उदाहरण: 5 जंपिंग जैक करो! गाओ "जन्मदिन मुबारक" आदि._

![अगले हॉप में जाने से पहले चुनौतियों कर रही शिक्षार्थियों की एक तस्वीर](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

जब पैकेट हॉप की चुनौती पूरी होती है, हॉप के पैकेट "वेबसाइट" जब तक पैकेट अगले स्थान पर ले जाने के लिए अनुमति देगा ।

दूसरे लोगों से पूछें की एक एकल फ़ाइल लाइन फार्म बनाये और उसके  रूप में जल्दी बाधा कोर्स के माध्यम से स्थानांतरित करें ! आप इसे यह सबसे तेजी से बनाना है जो देखने के लिए पाठ्यक्रम के माध्यम से प्राप्त करने के लिए हर किसी को कितना समय लगता है और कितना समय हो सकता है ।

![गतिविधि खेलने के लिए एक भी लाइन के निर्माण के शिक्षार्थियों की एक तस्वीर](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

१ ० <बी  आर >मिनट 
### प्रतिबिंब

सभी शिक्षार्थियों बाधा कोर्स पूरा करने के बाद, पैकेट वास्तविक जीवन में इंटरनेट के माध्यम से स्थानांतरित करने के लिए सक्षम हैं वो भी कितनी जल्दी से !

_अगर आपके पास इंटरनेट कनेक्टिविटी नई है और समय भी काम है तो आप पिंग यूटिलिटी गतिविधि छोड़ सकते हैं ._

समूह की तरह कुछ चिंतनशील सवाल पूछें:

> - यह वेबसाइट करने के लिए इंटरनेट के माध्यम से कंप्यूटर से सभी तरह पाने के लिए आप कितना समय लेंगे ?
> - क्या आपके लगता है की कंप्यूटर इंटरनेट के माध्यम से तेज़ चलता है जितना आप करते हैं ?
> - क्या होता जब आप इंटरनेट पे वेब एड्रेस टाइप करते है वो एंटर दबाते है ?
> - इंटरनेट के क्या क्या भाग हैं ?
> - जानकारी की बड़ी मात्रा में कभी नेट के कम बैंडविड्थ भागों के माध्यम से यह कैसे कर सकते हैं ?
> - इंटरनेट और वर्ल्ड वाइड वेब के बीच अंतर क्या है?

कुछ अनुमान ले लो और फिर हम वास्तव में एक असली अनुरोध कमान के तत्काल में पिंग उपयोगिता (पीसी) या टर्मिनल (मैक ) का उपयोग कर लेंगे और  वास्तव में कितनी देर बता सकते हैं ये भी समझाएं । अगर आप ऑफ़लाइन हैं तो बस समझाइये की क्या होगा !

```
पिंग एक ऐसा कार्य है कंप्यूटर में जो आपको दिखता है की आपके कंप्यूटर दूसरे कंप्यूटर से कनेक्ट हो सकता है नेटवर्क के माध्यम से या फिर ऑनलाइन किसी जानकारी का पैकेट भेज के और देखता है की वापस आने में पैकेट को कितना समय लगता हैं !
```

![गतिविधि पर चर्चा करते समय शिक्षार्थियों की एक तस्वीर](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

यह गूगल पिंग और वापस आने के लिए 5 पैकेट के लिए कितना समय लगाने के लिए  विशिष्ट अनुमान / दांव बनाने के लिए छात्रों से पूछो । दीवार पर उनके अनुमान को नीचे लिखें।

या तो समूहों में (उपकरण उपलब्ध है) या एक समूह प्रोजेक्टर पर देख रहे हैं , के रूप में google.com पर पिंग उपयोगिता ( निर्देश के लिए टिप शीट का उपयोग करें! ) चलाते हैं।

परिणामों पर चर्चा  करें .

को पूरा करें [पोस्ट - गतिविधि प्रश्नावली](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Thanks a lot for the awesome work!!!! :smile_cat: it is available at http://mozilla.github.io/mozilla-club-activity-ping-kong/#hi
