### ISSUE TITLE
Localization of aside.md into Filipino

### ISSUE THREAD

**Issue by UndercoverWerewolf** [mozilla/mozilla-club-activity-ping-kong#13]
#### Mga gagamit
- 8+
- para sa mga baguhan na may mapanuring pag-iisip
  #### Materyales
- Mga papel at panulat
- Web browser
- (opsyonal) [naka-print na HTML cheatsheet](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17418/)
- (opsyonal) [naka-print na gabay pangrepensiya ng X-Ray Goggles](https://d157rqmxrxj6ey.cloudfront.net/amaciel/17419/)
#### Mga Layuning Kailangang Matutunan
- Malaman ang pagkakaiba sa pagitan ng orihinal na gawa at ng nabago na
- Gamitin ang X-Ray Goggles para mabago ang isang web page nang mabigyan ito ng isang partikular na tema
- Bigyang puna ang gawa ng ibang baguhan
#### Aktuwal na aktibidad!

![Imahe](http://mozilla.github.io/webmaker-curriculum/images/hackthenews-action.jpg)
[Hive Pittsburgh: Pittsburgh Project Youth Get Hacking](http://hivepgh.sproutfund.org/blog/2014/12/15/pittsburgh-project-youth-get-hacking/)
#### Tingnan ang gawa ng ibang komunidad

Alamin ang mga paraan kung paano binago ng mga tagapagturo at ng mga aktibista ang aktibidad na ito para mga natatanging gagamit sa ating [Discussion Forum](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Awesome contribution! Thanks a lot for this awesome work, it is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#fil

Can you help me with translating "Web Mechanics" and "Navigation" into Filipino please?

:smiley_cat:
