### ISSUE TITLE
Localization of activity.md into Filipino

### ISSUE THREAD

**Issue by UndercoverWerewolf** [mozilla/mozilla-club-activity-ping-kong#14]
---

title: Ping Kong
github: mozilla/mozilla-club-activity-ping-kong
image: pingkong.png
competencies:
    - {label: "Web Mechanics", type: "web-mechanics"}
### Ping Kong

Likha ng [MOUSE](http://mouse.org/) kabilang ang mga larawan, Chad Sansing, at binago para sa Clubs ng [Mozilla](https://webmaker.org/mentor).

Para sa karamihan, ang "Internet" ay isang abstract at nakaka-overwhelm na konsepto. Ang gawaing ito ay hinahamon ang mga nais matuto na **makapag-isip nang konkreto patungkol sa kung paano nakikipag-ugnayan ang internet sa isang computer.**

1-2 oras
### Paghahanda

**Kumpletuhin ang** [pre-activity questionnaire](http://goo.gl/forms/Uua6yKIy5E).

Sunod, **gawin ang aktibidad sa sarili lamang** para maging pamilyar dito.

**Maging pamilyar** sa mga sumusunod na [termino](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. Command line/Command Prompt
2. Hop
3. Internet Protocol (IP) Address
4. Internet Service Provider (ISP)
5. Web Server
6. Local Area Network (LAN)
7. Packet
8. Ping
9. Router
10. Traceroute

**I-print at gupitin** ang [Ping Kong obstacle course signs](http://www.mousesquad.org/files/u4/pingkongcards.png).

**Magbigay ng kaukulang espasyo** sa iyong silid para sa isang "obstacle course." **Isabit ang cards** na may label na "My computer" at "The Website" sa magkabilang dulo ng silid.

![Ping Kong Cards](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

10<br>minuto
### Panimula

Tanungin ang mga mag-aaral, _"Paano mo mapupuntahan ang Internet?"_

Kumuha ng ilang ideya mula sa grupo, at saka ipaliwanag ang mga sumusunod:

![internet graphic](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)

> Ang "Internet" ay isang sistema ng networks at ang "web" ay matatagpuan sa tuktok ng internet at nagbibigay ng interface para sa pagtingin at pakikipag-ugnayan gamit ang impormasyon na nakaimbak sa iba't ibang computer sa buong mundo. Ang maikling artikulong ito mula sa Skillcrush ay mas lalong ipinapaliwanag ang kaibahan ng Internet sa Web. 

Ipaliwanag pa na:

> Sa tuwing uutusan mo ang Internet na gumawa ng isang bagay, paglalagay man ng URL sa brower o panonood ng video sa YouTube, isang lundag o "hop" ang isinasagawa ng iyong internet request gamit ang iilang network devices, tulad ng routers at switches at servers, mula sa iyong computer patungo sa server ng website.

Panoorin ang panimulang video para mabigyan ang mga mag-aaral ng kaukulang kaalaman bago simulan ang obstacle course:
#### There and Back Again: A Packet's Tale

[![There and Back Again: A Packet's Tale](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

15<br>minuto
### Gumanap Bilang Net

Bumuo ng maliit na grupo na binubuo ng 4-5 aktor. Magsama-sama at mag-isip ng paraan para isagawa kung paano gumana ang Internet. Pag-isipan kung paano gagamitin ang espasyo - kahit saan ay puwede kang mag-perfrom basta't may kaukulang espasyo sa paligid kung saan ka makakagalaw sa paraan na gusto mo. Isipin ang mga materyales sa paligid at kunin ang mga props na sa tingin mo'y magagamit mo sa pagpapakita ng aksyong kailangang gawin.

Isagawa ang skits para sa isa't isa. Taos-pusong bigyan ng pagpupugay ang ibang grupo. Makitawa't makisaya sa mga magagandang tagpo sa istorya ng Pagganap Bilang Net!

---

5<br>minuto
### Isaayos ang obstacle course

Sabihin na para mabilis na maintidihan ang gagawin, kailangan niyong **umakto bilang taong ping/traceroute sa isang obstracle course.**

Maglalakbay kayo mula sa isang i) local computer gamit ang ii) LAN patungo sa iii) Internet para makarating sa iv) Google.com o ang websit na iyong pinili.

![Isang larawan ng obstacle course](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

Sabihan ang grupo na **tumungo sa ilalim ng palatandaan na "My computer"** at magtawag ng **tatlong volunteer.***

Bigyan ang tatlong volunteer ng mga palatandaan na may label na **"Hop 1: Local Router," "Hop 2: Internet Service Provider" at "Hop 3: The Website Company's Router"** at sabihan na kailangan nilang tumungo sa iba't ibang parte ng silid.

Ipaliwanag na ang **mga palantadaan ay sumisimbolo sa iba't ibang "hops"** na kailangang daanan ng isang Internet request bago ito makapunta sa websit na hinahanap ng gumagamit. Ang **mga nalalabing mag-aaral** ay packets ng computer code  na nais makapunta sa website sa kabilang dulo ng silid.

![Isang larawan ng tagapangasiwa na ipinapaliwanag ang mga palatandaan](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

10<br>minuto
### Modelo ng obstacle course

**Mamili ng isa mula sa mga mag-aaral na nagsisilbing "packet" na gumanap bilang isang modelo** para sa grupo bago sila magsimula sa aktibidad.

Bigyan ang mga mag-aaral ng kaukulang senaryo

> Nasa harap ako ng aking computer at naisip ko na manood ng video sa YouTube. Pagkatapos kong i-type ang web address, ang aking computer ay ginagawang code ang 'youtube.com' na mababasa ng lahat ng computer at saka hinahati ang code sa iilang internet "packets." Ang nagboluntaryong mag-aaral ay sumisimbol sa isa sa packets na iyon.

![Larawan ng aktibidad na aktuwal na nagaganap at isang indibiduwal na naglalaro bilang isang local router.](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### Hop 1: Local Router

Sabihan ang ehemplong mag-aaral na maglakad patungo sa "Hop 1: Local Router" at ipaliwanag na:

> Una, ang packet ay lulundag gamit ang local network devices tulad ng routers, switches o modems ng kanilang gusali. Ang local network devices ang siya namang magpapadala ng packet sa Internet.
#### Hop 2: Internet Service Provider

Paglakarin ang mag-aaral sa susunod na hop at ipaliwanag ito:

> Pagkatapos makarating ang packet doon, sa Internet service provider, ito ay ipapadala patungo sa isa sa router ng YouTube.
#### Hop 3: Company Router

> Kapag nakadaan na ang packet sa router ng YouTube, dadalhin na ito sa isang computer ng headquarters ng kompanya na siyang magsasagawa ng streaming ng video.
#### Website

> Para magawang mag-stream ng video sa ating computer, ginagawang packets din ng computer ng YouTube ang video, na siya naman pupunta sa ating computer sa parehong daan ng network devices na ginamit natin para makarating sa YouTube.

**Sabihan ang halimbawang mag-aaral na maglakad pabalik sa iyo,** siguraduhin na titigil ito sa bawat lundag niya sa kanyang pagbalik.
#### IP Addresses

Kapag nakabalik na ang mag-aaral, magtanong kung may isa ba sa kanila ang may alam kung papaano nalalaman ng devices kung saan ipapadala ang packet sa bawat hop nito. Kung wala sa kanila ang nakaaalam, ipaliwanag na:

> Gumagamit sila ng IP addresses! Bawat device o computer sa isang netweork o online ay may IP (o "Internet Protocol") address. Para itong home address - at nakatutulong ito para mahanap ng devices ang isa't isa at para makipag-ugnayan. Ang IP addresses ay may 4 na set ng numero sa anyong tulad nito: 172.168.3.12
#### Sa Pagitan ng Bawat Hops

Para maging mas lalong kawili-wili ang obstacle course, maaari kang maglagay ng "government spies" sa pagitan ng bawat hops. [Ang resource mula sa EFF](https://www.eff.org/pages/tor-and-https) ay ipinapaliwanag kung paano na ang third parties ay may kakayahang mag-intercept ng data sa pagitan ng bawat hop. Ipaliwanag sa mga mag-aaral ang tungkol sa kung aling data ang protektado, alin ang hindi ligtas, at para kanino.

---

15<br>minuto
### Simulan na ang Race!

Ngayon, simula na para subukan ng lahat ang obstacle course!

**Ipaliwanag sa mga mag-aarala na silang lahat ay "packets"** na nais makarating sa Google.com (o sa website na nais nila) para makumpleto ang Internet request ng isang tao. Kailangan nilang tumigil sa bawat lundag o "hop" bago magpatuloy sa kasunod.

**Teka lang, may twist pa!** Bago makarating ang packets mula sa isang hop patungo sa kasunod, kailangan nilang makumpleto ang mabilis na hamon na ibabahagi ng mag-aaral na gumaganap bilang Hop. _Halimbawa: Isagawa ang 5 jumping jacks! Kumanta ng "Happy Birthday" etc._

![Isang larawan ng mga mag-aaral na isinasagawa ang mga hamon bago makapunta sa susunod na hop](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

Kapag ang packet ay nakumpleto na ang hamon ng Hop, ang Hop ay hahayaan nang makapunta ang packet sa susunod nitong paroroonan hanggang sa makarating ang packets sa "Website."

Sabihan ang packets na bumuo ng isang linya at tumungo sa obstacle course sa bilis na kanilang makakaya! Maaaring mag-takda ka ng kukuha ng oras kung gaano katagal ang lahat na makarating sa course para malaman kung sino ang mas mabilis.

![Isang larawan ng mga mag-aaral na gumagawa ng isang linyo para gawin ang aktibidad.](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

10<br>minuto
### Pagninilay-nilay

Matapos makumpleto ng lahat ng mag-aaral ang obstacle course, ipakita sa kanila kung gaano kabilis gumalaw ang mga packets sa Internet sa totoong buhay.

_Kung wala kang internet connectivity o kaya'y gahol na sa oras, huwag nang gawin ang Ping Utility exercise._

Tanungin ang grupo ng iilang mapawaring tanong tulad ng:

> - Gaano katagal ang aabutin mula sa computer gamit ang Internet patungo sa website?
> - Sa tingin mo ba, mas mabilis makapasok sa Internet ang computer kaysa sa iyo?
> - Ano ang mangyayari kung sa Internet ay inilagay mo ang web address at pinindot ang enter?
> - Ano-ano ang mga "bahagi" ng Internet?
> - Gaano kalaking impormasyon ang makararaan sa mga bahaging may low bandwith sa Net?
> - Ano ang kaibahan ng Internet sa World Wide Web?

Mamili ng ilang hula at saka ipaliwanag na puwede nating malaman kung gaano katagal aabutin ang isang tunay na request gamit ang Ping utility sa Command Prompt (PC) o Terminal (Mac). O kung ika'y offline, ipaliwanag mo na lang kung ano ang mangyayari.

```
Ang Ping ay isang function sa mga computer kung saan makikita mo kung ang iyong computer ay maaaring kumunekta sa ibang computer sa isang network o online sa pamamagitan ng pagpapadala ng 'packet' ng data rito at para makita kung gaano katagal ang aabutin ng packet para makabalik.
```

![Isang photo ng mga mag-aaral na ipinapaliwanag ang aktibidad](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

Sabihan ang mga mag-aaral na gumawa ng natatanging hula/pusta sa kung gaano katagal aabutin ang 5 packets para i-ping ang Google at saka bumalik. Isulat ang kanilang mga hula sa pader.
Pag-usapan ang mga naging resulta.

Kumpletuhin ang **[post-activity questionnaire](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Awesome contribution! Thanks a lot for this awesome work, it is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#fil

Can you help me with translating "Web Mechanics" and "Navigation" into Filipino please?

:smiley_cat:
