### ISSUE TITLE
Localization of activity.md into Gujarati

### ISSUE THREAD

**Issue by moingshaikh** [mozilla/mozilla-club-activity-ping-kong#17]
### પીંગ કોંગ

[માઉસ](http://mouse.org/) દ્વારા બનાવાયું અને [મોઝીલા](https://webmaker.org/mentor) દ્વારા ક્લબ માટે મિશ્રિત કરાયું.
ઘણા લોકો માટે, "ઇન્ટરનેટ" એક અમૂર્ત અને જબરજસ્ત ખ્યાલ છે. આ પ્રવૃત્તિ શીખનારાઓ ને પડકાર આપે છે કે એ શીખવા માટે કે કોમ્પ્યુટર ઈન્ટરનેટ સાથે કઈ રીતે સંચાર કરે છે.

દરમ્યાન, **આ ઉપરાંત તેઓ શોધ શબ્દો, શબ્દો પણ શીખશે અને કઈ રીતે વેબ ના સ્ત્રોતો ની માન્યતા અને અનુરૂપતા ની આકારણી કરવી એ પણ શીખશે.**
૧-૨ કલાક.
### તૈયારી

[પૂર્વ-ગતિવિધિ પ્રશ્નોતરી](http://goo.gl/forms/Uua6yKIy5E) **ને પૂરી કરો**

**આગામી**: તમારી રીતે પ્રવૃત્તિ કરો જેથી તમે એનાથી વધુ સારી રીતે પરિચિત થાઓ 

નિમ્નલિખિત [શબ્દો](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary) સાથે તમારી જાત ને પરિચિત કરો:
1. કમાન્ડ લાઈન
2. હોપ 
3. ઈન્ટરનેટ પ્રોટોકોલ (આઈપી) એડ્રેસ 
4. ઈન્ટરનેટ સર્વિસ પ્રદાતા (આઇએસપી)
5. વેબ સર્વર
6. લોકલ એરિયા નેટવર્ક (લાન)\
7. પેકેટ 
8. પીંગ 
9. રાઉટર
10. ટ્રેસરૂટ  

**પ્રિન્ટ કરો અને કાપો**: [પીંગ કોંગ કોર્સ અવરોધ ચિહ્નો](http://www.mousesquad.org/files/u4/pingkongcards.png)
પીંગ કોંગ કોર્સ માટે તમારા ઓરડા માં પુરતી જગ્યા સાફ કરો ઓરડા ની વિરુદ્ધ દિશા માં "મારું કમ્પ્યુટર" અને "વેબસાઈટ" કરીને કાર્ડ **ને ટીંગાડી દો**.

૧૦
મિનીટ 
### પરિચય

વિદ્યાર્થીઓને પૂછો તેઓ ઈન્ટરનેટ કઈ રીતે મેળવે છે?

![](https://camo.githubusercontent.com/23d243e7e22e7d03153e7eb7b18612387d581804/687474703a2f2f346239336e33327177766a6a3364646e357733796866666f6173362e7770656e67696e652e6e6574646e612d63646e2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031332f30332f696e7465726e657476737468657765622e6a7067)

> આ "ઇન્ટરનેટ" નેટવર્ક આધારિત એક પ્રણાલી છે અને "વેબ" તે પ્રણાલી ની ટોચ પર બિરાજે છે દુનિયાભર ના કોમ્પ્યુટર્સ માં સંગ્રહિત માહિતી જોવા અને  વાતચીત કરવા માટે ની એક > સપાટી પૂરી પડે છે. સ્કીલ્ક્ર્ષ નું આ ટૂંકું  લેખ વધુ ઇન્ટરનેટ અને વેબ વચ્ચે નો વધુ તફાવત સમજાવે છે.

વધુ માં સમજાવો કે:

> જયારે પણ તમે ઈન્ટરનેટ ને કઈ પણ કરવા માટે કઈ પણ કરવા માટે પૂછો છો, ભલે એ બ્રાઉસર માં યુ.આર.એલ. લખીને કે યુટ્યુબ પર વિડીયો જોઈને, તમારી ઈન્ટરનેટ "વિનંતી"  > ઘણા બધા નેટવર્ક ઉપકરણો જેવા કે, રાઉટર્સ અને સ્વીચો અને સર્વર માં થી થઇ ને તમારા કોમ્પ્યુટર પર થી વેબસાઈટ ના સર્વર પર જાય છે.

અવરોધ અભ્યાસક્રમ શરુ કરતા પહેલા તમારા વિદ્યાર્થીઓ ને થોડો વધુ સંધર્ભ આપવા માટે પ્રારંભિક વિડીયો જુઓ.
### ત્યાં અને પાછા: એક પેકેટ ની કથા

![](https://camo.githubusercontent.com/d7db0c91fa01c36810f7f32f522bbcd7fde779db/687474703a2f2f696d672e796f75747562652e636f6d2f76692f5777794a477a5a6d4265382f302e6a7067)

૧૫
મિનીટ 
### નેટ ને ભજવો

૪-૫ નાના અભિનેતાઓ નો સુધાર સમૂહ બનાવો. સાથે ભેગા થઇ ને વિચાર-વિમર્શ કરો કે કઈ રીતે ભજવી શકાય કે ઈન્ટરનેટ કઈ રીતે કામ કરે છે. તમારી જગ્યા કઈ રીતે ઉપયોગ માં લેવી એના વિષે વિચારો. તમે ક્યાય પણ ભજવી શકો છો. ત્યાં તમારી આસપાસ જગ્યા માં ઓરડો છે અને તમે જેટલા ઈચ્છો તેટલા બહાર નીકળો અને ફરો. તમારી આસપાસ રહેલી સામગ્રી - સમાન વિષે વિચારો અને જે વસ્તુ તમને યોગ્ય લાગે નેટ ની કાર્યપદ્ધતિ સમજવવા માટે, તેને લઇ લો. એક બીજા ના માટે નેટ ભજવો. અને બીજા સમૂહો માટે ખુલ્લા દિલ થી વખાણ કરો અને વધાવો. નેટ ભજવવાના નાટક ની ખાસ ક્ષણો પર હસો અને ખુશ થાઓ.

૫
મિનીટ
### અવરોધ અભ્યાસક્રમ ગોઠવો

કહો કે આ રસ્તા ને સમજવા માટે આપણે **એક માનવ પીંગ / ટ્રેસરૂટ તરીકે ભાગ ભજવીશું**

આપણે એક યાત્રા કરીશું ૧) સ્થાનિક કોમ્પ્યુટર ના માધ્યમ થી ૨) એક સ્થાનિક નેટવર્ક થી ૩) ઈન્ટરનેટ ૪) google.com અથવા તમારી પસંદ ની કોઈ પણ વેબસાઈટ પર જવા માટે.
![](https://camo.githubusercontent.com/e76609502d73eda3564ccaa77b4b5932e63d780d/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383036362f383233323336353639335f643739646462313966375f622e6a7067)

સમૂહ ને **"મારું કોમ્પ્યુટર" સંજ્ઞા નીચે ભેગા થવા** કહો અને **૩ સ્વયંસેવકો** ને કહો.

**ત્રણ સ્વયંસેવકો ને "હોપ ૧: લોકલ રાઉટર", "હોપ ૨: ઈન્ટરનેટ સેવા પ્રોવઈડર", અને  "હોપ ૩વેબસાઈટ કમ્પની નું રાઉટર"** અને તેમને સમગ્ર ઓરડામાં બહાર પ્રસરી જવા કહો. 
તેમને સમજાવો કે **ત્રણ સંજ્ઞાઓ જુદા જુદા "હોપ" દર્શાવે છે** કે જ્યાં ઈન્ટરનેટ વપરાશકર્તા જે વેબસાઈટ પર જવા માંગે છે એ વેબસાઈટ પર જતા પહેલા એ હોપ સમક્ષ જાય છે.
ઓરડા ના બીજા છેડે રહેલ **બાકી ના વિદ્યાર્થીઓ** કોમ્પ્યુટર કોડ ના પેકેટ છે જેઓ વેબસાઈટ પર જવાનું પ્રયત્ન કરી રહ્યા હોય છે. 
![](https://camo.githubusercontent.com/b09efa83822de36576d20b2b93c5565b161ef1d9/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383335302f383233323336373131355f333636326562663135345f622e6a7067)

૧૦
મિનીટ
### અવરોધ અભ્યાસક્રમ મોડેલ કરો

બાકી ના સમૂહ માટે, એ પહેલા કે બધા છાત્રો પ્રવૃત્તિ શરુ કરે, *_આમાં ના "પેકેટ" વિદ્યાર્થીઓ માં થી એક ને મોડેલ તરીકે પસંદ કરો *_

વિદ્યાર્થીઓ ને નિમ્નલિખિત દૃશ્ય આપો. 

> હું મારા કોમ્પ્યૂટર ઉપર છુ અને મેં યુટ્યુબ ઉપર એક વિડીઓ જોવાનું નિર્ણય કર્યો છે. જેવું હું વેબ અડ્રેસ લખું છુ એ પછી મારું કોમ્પ્યુટર 'યુટ્યુબ.કોમ' ને બધા કોમ્પ્યુટર્સ વાંચી શકે એવા કોડ માં રૂપાંતરિત કરે છે અને પછી એ કોડ ને ઘણા બધા ઈન્ટરનેટ "પેકેટ્સ" માં વિભાજીત કરે છે. આ સ્વયંસેવક વિદ્યાર્થીઓ એ પૈકી ના પેકેટ્સ નુ પ્રત્નીધીત્વ કરે છે.
> ![](https://camo.githubusercontent.com/92dd0c02440321d6e84e0623eb807723c4711d7b/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383438312f383233333433303538345f636535396234613534365f622e6a7067)
### હોપ ૧: લોકલ રાઉટર

આ "હોપ ૧:લોકલ રાઉટર" જવા ઉદાહરણ વિદ્યાર્થીઓ ને કહો અને સમજાવો:

> પ્રથમ, તમારા બિલ્ડીંગ માં રહેલા લોકલ નેટવર્ક યંત્રો જેવા કે રાઉટર્સ, સ્વીચીસ અથવા મોડેમ્સ માંથી પેકેટ પસાર થશે. ત્યાર બાદ લોકલ નેટવર્ક યંત્રો પેકેટ ઈન્ટરનેટ ને મોકલશે.
### હોપ ૨: ઈન્ટરનેટ સર્વિસ પ્રોવાઈડર

વિધાર્થીઓ ને એમાં ચલાવો અને આગળ ના હોપ વિષે સમજાવો
### હોપ ૩વેબસાઈટ કમ્પની નું રાઉટર

એક વખત પેકેટ યુટ્યુબ ના રાઉટર માં થી પસાર થઇ જાય છે ત્યાર બાદ એ કંપની ના મુખ્ય મથક ના એક ક્મ્પ્યુર માં મોકલવામાં આવે છે જે મારા વિડીયો નું પ્રસારણ કરશે.
### વેબસાઈટ

વિડીઓ મારા કોમ્પ્યુટર માં પ્રસારિત થાય એ માટે યુટ્યુબ નું કોમ્પ્યુટર મારા વિડીઓ ને પણ પેકેટ્સ માં રૂપાંતરિત કરે છે જે મારા કોમ્પ્યૂટર પર બધી રીતે પાછો  આવે છે એ જ નેટવર્ક યંત્રો ના રસ્તે થી જ્યાંથી એ યુટ્યુબ માં ગયો હતો. 
### આઈ.પી.એડ્રેસીસ

જયારે વિદ્યાર્થીઓ પાછા આવે ત્યારે, એમને પૂછો કે એમનું કોઈ જાણે છે કે દરેક હોપ પર યંત્રો ને બરોબાર ખબર પડે છે કે પેકેટ ક્યાં મોકલવાના છે, જો કોઈ પણ વિદ્યાર્થી ને ના ખબર હોય તો એમને સમજાવો:
### હોપ્સ ની વચ્ચે

અવરોધ અભ્યાસક્રમ ને વધુ રસપ્રદ બનાવવા માટે તમે  હોપ્સ ની વચ્ચે "સરકાર જાસુસી કરે છે" મૂકી શકો. [EFF માના આ સંસાધનો](https://www.eff.org/pages/tor-and-https) સમજાવે છે કે કઈ રીતે ત્રીજો પક્ષ હોપ્સ ની વચ્ચે દાખલ થઇ માહિતી ને રોકી શકે છે. તમારા વિદ્યાર્થીઓ જોડે ચર્ચા કરો કઈ માહિતી સુરક્ષિત રખાય છે અને કઈ માહિતી સંવેદનશીલ છે અને કોના પ્રતિ.

૧૫
મિનીટ 
### દોડ માટે રવાના

હવે સમય છે બધા માટે અવરોધ અભ્યાસક્રમ ની કોશિશ કરવાનો!

બધા વિદ્યાર્થીઓ ને સમજાવો કે **તેઓ બધા "પેકેટ્સ" છે** જેઓ કોઈ ની ઈન્ટરનેટ રીક્વેસ્ટ ને પૂરી કરવા માટે ગુગલ.કોમ (અથવા તમારી પસંદ ની કોઈ બીજી વેબસાઈટ) તરફ જઈ રહ્યા છે.

**પણ થોભો, અહિયાં એક વળાંક છે!** આ પહેલા કે પેકેટ્સ એક હોપ થી બીજા હોપ તરફ જાયે , તેઓએ હોપ તરીકે વર્તી રહેલા વિદ્યાર્થીઓ દ્વારા મુકવા માં આવેલ એક પડકાર ને પૂરું કરવું જ પડશે.

ઉદાહરણ: ૫ જમ્પિંગ જેક કરો! "જન્મદિન મુબારક" ગાઓ, ઈત્યાદી.

![](https://camo.githubusercontent.com/1853976234524d896f2f09c1e8d07a1363726fea/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383334322f383233333433303338365f343561356162613039615f622e6a7067)

જયારે પેકેટ્સ હોપ નો પડકાર પૂરું કરી લેશે ત્યારે હોપ પેકેટ ને જ્યાં સુધી "વેબસાઈટ " પર પહોચી ના જાય ત્યાં સુધી આગળ ના સ્થાન પર જવા માટે અનુમતિ આપશે. પેકેટ્સ ને એક રેખા રચવાનું કહો અને બને તેટલી ઝડપથી અવરોધ અભ્યાસક્રમ માંથી પસાર થવા કહો. કોણ કેટલું સમય લે છે તે જોવા માટે તમે કોઈ એક ને સમય નોંધવા માટે કહી શકો છો જેથી તમે જોઈ શકો કે સૌથી ઝડપ થી અભ્યાસક્રમ માંથી પસાર કોણ થાય છે. 
![](https://camo.githubusercontent.com/cdc28066a603eca7aec54cfd9838198abbe99ed3/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383230372f383233333433303132305f656130633766633766615f622e6a7067)

૧૦
મિનીટ
### પ્રતિબિંબ

જયારે બધા વિદ્યાર્થીઓએ અવરોધ અભ્યાસક્રમ પૂરું કરી લે ત્યાર બાદ, તેમને દેખાડો કે વાસ્તવિકતા માં કેટલી ઝડપ થી પેકેટ્સ ઈંટરનેટ  માંથી પસાર થઇ શકે છે.

જો તમારી પાસે ઈન્ટરનેટ ક્નેતીવીટી ના હોય કે સમય નો અભાવ હોય તો પીંગ ઉપયોગીતા કસરત અવગણી શકો છો. 

સમૂહ ને થોડા પ્રતિબિંબીત પ્રશ્નો પૂછી શકો જેવા કે: 

> - ઈન્ટરનેટ દ્વારા તમારા કમ્પ્યુટર થી વેબસાઈટ પર જવા માં તમને કેટલો સમય લાગ્યો?
> - શું તમને લાગે છે કે એક કોમ્પ્યુટર તમાર કરતા વધુ ઝડપથી ઈન્ટરનેટ માંથી પસાર થાય છે?
> - જયારે તમે એક વેબસાઈટ સરનામું લાખો છો અને એન્ટર કી દબાવો છો ત્યારે શું થાય છે?
> - ઈન્ટરનેટ ના ભાગો કયા કયા છે?
> - મોટા કદ ની માહિતી કઈ રીતે નેટ ના નાની બેન્ડવિથ ના ભાગો કઈ રીતે પસાર કરે છે?
> - ઈન્ટરનેટ અને ધ વર્લ્ડ વાઈડ વેબ વચ્ચે શું ફરક છે?
> - ઈન્ટરનેટ દ્વારા તમારા કમ્પ્યુટર થી વેબસાઈટ પર જવા માં તમને કેટલો સમય લાગ્યો?

થોડા અનુમાન મેળવો અને પછી સમજવો કે આપણે કમાંડ પ્રોમ્પ્ટ (પી.સી.) અથવા ટર્મિનલ (મેક) માં પીંગ ઉપયોગિતા દ્વારા કઈ રીતે કહી શકીએ કે વાસ્તવિક રીક્વેસ્ટ કેટલો સમય લે છે. અથવા જો તમે ઓફ્ફલાઈન છો તો ફક્ત સમજવો છે શું થશે.

Ping is a function on computers that lets you check to see if your computer can connect to another computer over the network or online by sending a ‘packet’ of data to it and seeing how long it takes for the packet to come back.

<pre><code>પીંગ એ કોમ્પ્યુટર પર એક એવો કાર્ય છે કે જે તમને માહિતી નો એક 'પેકેટ' મોકલી ને તપાસવા દે છે કે તમારો કોમ્પ્યુટર બીજા કોમ્પ્યુટર નેટવર્ક દ્વારા અથવા ઓનલાઈન જોડાઈ શકે છે કે નહિ અને પેકેટ ને પાછો આવતા કેટલો સમય લાગે છે એ પણ બતાવે છે. 
</code></pre>

![](https://camo.githubusercontent.com/8d9958606f1f9c2f79ea7c4f42676985a3ad371b/68747470733a2f2f6661726d392e737461746963666c69636b722e636f6d2f383438342f383233333433313335325f643831376535353366615f622e6a7067)

વિદ્યાર્થીઓ ને અનુમાન / શર્તો લગાવવા કહો કે 5 પેકેટ્સ ને ગૂગલ પર જવામાં અને પાછા આવવા માં કેટલો સમય લાગશે. તેમના અનુમાનો દીવાલ ઉપર લખો. યા તો સમૂહ માં (જો સાધનો ઉપલબ્ધ હોય તો) અથવા એક સમૂહ પ્રોજેક્ટર તરફ જોઈ રહ્યું હોય, ગૂગલ.કોમ પર પીંગ ઉપયોગિતા ચલાવો (સૂચનો માટે પત્રિકા નો ઉપયોગ કરો)

પરિણામ ની ચર્ચા કરો.

[પ્રવૃત્તિ બાદ ની કાર્યસુચી](http://goo.gl/forms/ezm6IXWhhM) પૂરી કરો.

**Comment by soapdog** [comment]
Awesome work! Thanks a lot for this contribution, it is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#gu

Can you help me with translating "Web Mechanics" and "Navigation" into Gujarati please?

:smile_cat:

**Comment by moingshaikh** [comment]
Below two strings are Gujarati translation for web mechanics and navigation, respectively.
- વેબ કાર્યપ્રક્રિયા.
- સંશોધક.

**Comment by soapdog** [comment]
Thanks a lot! I've picked them from the other issue you posted. :+1:
