### ISSUE TITLE
Localization of aside.md into Gujarati

### ISSUE THREAD

**Issue by moingshaikh** [mozilla/mozilla-club-activity-ping-kong#18]
### દર્શકગણ

૮+
પ્રણાલી વિચારકો થી શરૂઆત 
### સામગ્રી
- મુદ્રિત [અવરોધ અભ્યાસક્રમ સંજ્ઞાઓ](http://www.mousesquad.org/files/u4/pingkongcards.png)
- વેબ બ્રાઉસર (વૈકલ્પિક)
### શીખવાના ઉદ્દેશો
- શોધ શબ્દો વચ્ચે તફાવત, યુ.આર.એલ. અને આઈ.પી.અડ્રેસિસ.
- બે કમ્પ્યુટર્સ વચ્ચે માહિતી પ્રવાહ અનુસરો.
- વેબ અને ઇન્ટરનેટ વચ્ચે વ્યવહારુ તફાવતો વર્ણવો.
- ઓપન વેબ પર સાધનોની મદદથી સર્વરોના  ભૌતિક સરનામાં શોધો.
- એક વેબસાઈટ ના ગ્રંથકર્તા અને તેની સામગ્રી નું દસ્તાવેજીકરણ કરવું
### વિદ્યાર્થીઓ / શીખનારાઓ માર્ગદર્શક કઈ રીતે બને છે
- એક વિધાર્થી અથવા ઓછા અનુભવી પર પોતાની પ્રતીચાયા રાખો જેથી તેઓ ઝડપ થી આ પ્રવૃત્તિ ની આગેવાની લઇ શકે.
- જો અમુક વિદ્યાર્થીઓ ઝડપથી આગળ વધે છે અથવા આ પ્રવૃત્તિ માં વધુ આત્મવિશ્વાસ ધરાવે છે તો તેવા વિદ્યાર્થીઓ ને અન્ય સમૂહ ને માર્ગદર્શન આપવા કહો.
- અંત માં, વિદ્યાર્થીઓ ને આ પ્રવૃત્તિ પોતાના મિત્રો અને પારિવારિક સભ્યો ને શીખવાડવા કહો.
### સામુદાયિક રીમીક્સ જુઓ

કઈ રીતે શિક્ષકો અને કાર્યકરો એ તેમના ચોક્કસ / વિશેષ દર્શકગણ માટે આ પ્રવૃત્તિ ને સંશોધિત કરી છે એ અમારા [ચર્ચા-વિચારણા ફોરમ](https://discourse.webmaker.org/c/curriculum) માં જુઓ.

**Comment by soapdog** [comment]
Awesome work! Thanks a lot for this contribution, it is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#gu

Can you help me with translating "Web Mechanics" and "Navigation" into Gujarati please?

:smile_cat:

**Comment by moingshaikh** [comment]
Below two strings are Gujarati translation for web mechanics and navigation, respectively.
- વેબ કાર્યપ્રક્રિયા.
- સંશોધક.

**Comment by soapdog** [comment]
Thanks a lot! I've fixed them on the activity :+1:

The competencies buttons now show the correct Gujarati translation!

**Comment by moingshaikh** [comment]
Terrific!
