### ISSUE TITLE
Localization of aside.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-ping-kong#19]
#### Målgrupp
- 8+
- nybörjande systemtänkare
#### Material
- Utskrivna [Hinerbane skyltar](http://www.mousesquad.org/files/u4/pingkongcards.png)
- Webbläsare (valfritt)
#### Lärandemål
- Se skillnaden mellan sök termer, URL:er och IP adresser.
- Följ flödet av information mellan två datorer.
- Förklara dom praktiska skillnaderna mellan webben och internet.
- Leta reda på dom fysiska adresserna på servrar med hjälp av verktygen på den öppna webben.
#### Hur eleverna blir mentorer
- Skugga en student eller mindre erfarna handledare så att de kan öva på att leda denna verksamhet.
- Om vissa elever är snabbare och är mer självsäkra i verksamheten, be dem att hjälpa till i en annan grupp.
- Avsluta genom att uppmana eleverna att lära ut denna verksamhet till sina vänner och familj.
#### See remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt. [Diskussionsforum](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Yaaayyyy for more Swedish awesomeness!

Thanks a lot for the L10N, it now lives at http://mozilla.github.io/mozilla-club-activity-ping-kong/#sv

PS: Can you help me translate those buttons on the left sidebar? :smile_cat:

**Comment by bittin** [comment]
@soapdog yeah sure i can Navigation makes sense in Swedish aswell as its the same word but Web Mechanics should be Webb mekanik and the buttons on top should be 

```
#TeachTheWeb = #TeachTheWeb 
Discussion = Diskussion 
View on Github = Visa på Github
```

Will translate some more Markdown files for this, this or next week when i have some spare time :)

**Comment by soapdog** [comment]
I've fixed the web mechanics button. I am fixing the template there to make sure it has localizable navigation. I will be back here shortly...

thanks again for the help!

**Comment by soapdog** [comment]
Done! I've added new elements to `activity.md` to account for translating those items.

Thanks for the tip! :smile_cat:
