### ISSUE TITLE
Localization of activity.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-ping-kong#20]
thub: mozilla/mozilla-club-activity-ping-kong
image: pingkong.png
competencies:
    - {label: "Web Mechanics", type: "web-mechanics"}
### Ping Kong

Skapad av [MOUSE](http://mouse.org/) inkluderar bilder av Chad Sansing, och remixad för Clubs av [Mozilla](https://webmaker.org/mentor).

För många, är "Internet" ett abstrakt och övervälmande koncept. Denna aktivitet utmanar och lär ut utövaren att **tänka konkret om hur internet kommunicerar med en dator.**

1-2 timmar
### Förberelser

**Genomför** [Den förberedande Enkäten](http://goo.gl/forms/Uua6yKIy5E).

Gör **sedan aktiviteten själv** för att bekanta dig med den.

**Bekanta dig själv** med följande  [termer](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. Kommandolinje/Kommando Prompt
2. hopp
3. Internet Protokoll (IP) Address
4. Internet Service Provider (ISP)
5. Webb Server
6. Local Area Network (LAN)
7. Packet
8. Ping
9. Router
10. Traceroute

**Skriv ut och klipp ut** [Ping Kong  korten](http://www.mousesquad.org/files/u4/pingkongcards.png).

**Rensa tillräckligt med plats** i ditt rum room för att placera korten. **Häng upp korten** som det står "My computer" och "The Website" på olika sidor av rummet.

![Ping Kong Cards](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

10<br>min
### Introduktion

Fråga deltagarna, _"Hur får du åtkomst till Internet?"_

Ta några Idéer från gruppen, och sen förklara följande:

![internet grafik](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)

> "Internet" är ett system av nätverk och webben sitter på toppen av Internet och tillhandahåller ett gränssnitt för att visa och interagera med information. lagrad i flera olika datorer runt om i världen.  Denna korta artikel från Skillcrush förklarar mer om skillnaderna mellan Internet och Webben.

Förklara också att:

> Varje gång du frågar internet att göra nånting, oavsett om det är att skriva in en webbadress i en webbläsare eller kolla på en video på youtube, Så hopppar din internet fråga "hopps" runt flera nätverksenheter, som routrar och switchar och servrar, påväg från din dator till hemsidans server.
> Kolla på introduktions videon för att ge dom som ska lära sig lite mer kontext före ni börjar med hinderbanan:
#### There and Back Again: A Packet's Tale

[![Där och tillbaka igen: Ett Packet's resa](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

15<br>min
### Utför nätet

Bilda små improv grupper om 4-5 aktörer. Träffas och brainstorma ett sätt att utföra hur Internet fungerar. Tänk på hur du använder din plats - du kan utföra överallt där det finns plats i utrymmet omkring dig och sprida ut och röra dig så mycket som du vill. Tänk på materialen omkring dig och ta all rekvisita som kan hjälpa dig att visa hur nätet fungerar.
## Gör dina egna sketcher för varandra. Applådera ditt hjärta ut för de andra grupperna. Skratta och heja på särskilt stora stunder av Utföra Nätverkshistoria!

5<br>min
### Sätt upp en hinderbana

Säg att för att hjälpa oss förstå vägen that to help understand this path, we're going to **act out a human ping/traceroute in an obstacle course.**

Vi kommer att resa från en i) lokal dator genom ii) ett LAN till iii) Internet för att komma till iv) Google.com eller hemsidan du väljer.

![Ett foto av hinderbanan](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

Fråga gruppen att **samlas under "My computer" skylten** och fråga efter **tre volontärer.**

Ge tre av volontärerna skyltarna med texterna **"hopp 1: Lokal Router," "hopp 2: Internet Operatör och "hopp 3: Hemside företagets Router"** och be dom sprida ut sig i rummet.

Förklara att  **skyltarna  representerar olika "hopps"**  som en Internet-begäran måste gå igenom innan det blir till webbplatsen användaren är ute efter.  **Resten av eleverna** är paket av datakod som försöker gå till webbplatser i andra änden av rummet.

![Ett foto som visar en facilitator som förklarar skyltarna](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

10<br>min
### Modellera hinderbanan

**Välj en av dessa "packet" studenterna som ska fungera som en modell** för  resten av gruppen före alla börjar med aktiviteten.

Ge eleverna följande scenario

> Jag är på min dator och jag bestämmer mig för att titta på en video på YouTube. När jag skriver in webbadressen, omvandlar min dator "youtube.com" i en kod som alla datorer kan läsa och sedan delar denna kod i flera internet "paket". Denna frivilliga deltagare representerar ett av dessa paket.

![Ett foto som visar aktiviteten i handling och en person som spelar som en lokal router](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### hopp 1: Lokal Router

Be exempel eleven att gå till "hopp 1: Lokal Router" och förklara:

> Första paketet kommer att hopppa genom lokala nätverksenheter som routrar, växlar och modem i byggnaden. De lokala nätverksenheterna skickar därefter paketet till Internet.
#### hopp 2: Internetoperatör

Be eleven gå till och förklara nästa hopp:

> Efter ett paket kommer hit, till Internetleverantören, skickas det hela vägen till en av YouTubes routrar.
#### hopp 3: Företagets Router

> När paketet når till YouTubes router, ska det skickas till en dator i företagets huvudkontor som strömmar min video.
#### Hemsida

> För att få videon att strömma på min dator, konverterar YouTubes dator min video i paket också, vilket reser hela vägen tillbaka till min dator på samma väg som nätverksenheter som krävdes för att komma till YouTube.

**Be exempel eleven att gå tillbaka till dig,** och se till att pausa vid varje hoppp på vägen tillbaka.
#### IP Adress

När studenten återvänder, fråga om någon vet hur enheterna vid varje hoppp vet exakt var de ska skicka ett paket. Om ingen vet, förklara:

> De använder IP-adresser! Varje enhet eller dator i ett nätverk eller på nätet har en IP (eller "Internet Protocol") adress. Det är som en hemadress - och det hjälper enheter hitta varandra och kommunicera. IP-adresser har 4 uppsättningar siffror i en sträng så här: 172.168.3.12
#### I mellan hoppp

För att göra hinderbanan mer intressant, kan du placera "statliga spioner" mellan hoppp. [Denna resurs från EFF](https://www.eff.org/pages/tor-and-https) förklarar hur tredje parter kan fånga upp data mellan hoppp. Prata med dina elever om vad data skyddas, vad är sårbara, och till vem.

---

15<br>min
### Iväg till tävlingarna!

Nu är det dags för allihoppa att prova hinderbanan!

**Förklara för eleverna att dom är alla "paket"** som försöker ta sig till Google.com (eller webbplatsen du väljer) för att slutföra någons begäran på Internet. De måste stanna vid varje "hopp" innan vi går vidare till nästa.

**Men vänta, där finns en twist!** Innan paketen kan ta sig från ett hopp till nästa, så måste dom klara en snabb utmaning av studenten som agerar hoppare. _Exempel: Gör 5 Jumping Jacks! Sjung "Ja må han leva" osv_

![Ett foto som visar eleverna gör utmaningar innan du flyttar till nästa hopp](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

När paketet avslutar hopp utmaning, kommer hoppet att tillåta paketet för att flytta nästa plats tills paketen når "Webbplatsen".

Be paketen för att bilda en enda rak linje och gå igenom hinderbanan så snabbt som möjligt! Du kan ha någon tid hur lång tid det tar att alla ska få igenom kursen för att se vem som gör den till den snabbaste.

![Ett foto av eleverna att bygga en enda rak linje för att spela hinderbanan](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

10<br>min
### Reflektion

Efter alla elever har slutfört hinderbana, visa dem hur snabbt paket kan röra sig genom Internet i verkliga livet.

_IOm du inte har Internet-anslutning eller har ont om tid, hoppa över Pingfunktions träningen._

Fråga gruppen några reflekterande frågor som tex:

> *Hur lång tid tog det för dig att få hela vägen från datorn via Internet till webbplatsen?
> - Tror du att en dator går snabbare via Internet än vad du gjorde?
> - Vad händer på Internet när du skriver en webbadress och tryck enter?
> - Vilka är de "delar" av Internet?
> - Hur färdas stora mängder information någonsin genom låg bandbredd via Internet?
> - Vad är skillnaden mellan Internet och World Wide Web?

Ta några gissningar och sedan förklara att vi faktiskt kan säga exakt hur lång tid en riktig begäran tar med hjälp av pingverktyget i Kommandotolken (PC) eller Terminal (Mac). Eller om du är offline, bara förklara vad som skulle hända.

```
Ping är en funktion på datorer som låter dig kontrollera att se om din dator kan ansluta till en annan dator via nätverket eller online genom att sända ett "paket" av data till det och se hur lång tid det tar för paketet att komma tillbaka.
```

![Ett foto av eleverna diskutera aktiviteten](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

Be eleverna att göra särskilda gissningar / satsningar för hur lång tid det tar för 5 paket att pinga Google och komma tillbaka. Skriv ned sina gissningar på ett papper.

Antingen i grupp (om utrustning finns) eller som en grupp tittar på projektorn, kör ping på google.com (använd spetsbladet för instruktioner!).

Diskutera resultaten.

Genomför sedan den**[avslutande enkäten.](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Yaaayyyy for more Swedish awesomeness!

Thanks a lot for the L10N, it now lives at http://mozilla.github.io/mozilla-club-activity-ping-kong/#sv

PS: Can you help me translate those buttons on the left sidebar? :smile_cat:
