### ISSUE TITLE
Localization of activity.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-ping-kong#21]
---

title: Ping Kong
github: mozilla/mozilla-club-activity-ping-kong
image: pingkong.png
competencies:
    - {label: "Web Mechanics", type: "web-mechanics"}
### Ping Kong

Made by [MOUSE](http://mouse.org/) including photos, Chad Sansing, and remixed for Clubs by [Mozilla](https://webmaker.org/mentor).

相对于大多数的人来讲，上网是一个非常抽象的概念，*\* 本次活动的目的就是让学习者清楚感受到互联网如何与计算机进行通信。**

1-2 小时
### 活动的准备

**完成** [活动前期调查问卷](http://goo.gl/forms/Uua6yKIy5E).

接下来做你自己的活动来熟悉它。

**熟悉以下 [条款：](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. 命令行/命令提示符
2. 跃距 **两个节点间的逻辑距离,即一个跃距为从一个节点到邻近一个节点的距离.可能还有转发的意思**
3. 互联网协议（IP）地址
4. 互联网服务提供商（ISP）
5. 网络服务器
6. 局域网（LAN）的
7. 包（数据）
8. Ping
9. 路由器
10. 路由跟踪

**打印**  [本次活动 标识](http://www.mousesquad.org/files/u4/pingkongcards.png).

_留出足够的空间进行活动" *_把标识1.2分别放在房间的两侧*\*  标识1 **我的电脑(START)** ，标识2  **网站(END)**

![Ping Kong Cards](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

10<br>分钟
### 活动介绍

首先和参与者讨论, _"你是怎么上网的?"_

多了解几个参与者，之后总结一下:

![internet graphic](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)

> “互联网”是网络的系统和“网络”坐在因特网的顶部，并提供用于查看和与存储在世界各地的各种计算机中的信息进行交互的接口。从 [Skillcrush](http://skillcrush.com/2012/08/19/the-internet-vs-the-web/)这篇短文章中可以进一步解释了互联网和网络之间的区别。

进一步的解释：:

> 任何时候你都可以通过互联网做一些事情，无论是通过输入网址到浏览器或在YouTube上观看视频时，你的网络要求“跳（让学生理解一下本子是如何从第一排被传送到最后一排）”，通过多个网络设备，如路由器，交换机和服务器，按照互联网的方式从电脑到网站的服务器。

活动开始之前，和大家一起分享这个视频，让同学们更直观的了解互联网是如何运作的
#### 这里到那里：数据包的故事

[![There and Back Again: A Packet's Tale](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

15<br>分钟
### 模拟一个网络（基础网络）

可以随机安排 4-5 参与者组成一个小型的网络。集体讨论用什么方式来执行互联网是如何工作。想想如何使用您的**共享空间**,想想你周围有什么材料，抓住任何可能帮助你在工作中显示网的道具。尽可能的模仿网络是如何运作的原理

鼓励更多的人一起参与这个活动，共同分享合作的喜悦.

---

5<br>分钟
### 设计一个有设备的网络（服务器，路由器，网关等等）

和同学们一起讨论如何利用这些设备进入互联网，Google.com或您所选择的网站。

![A photo of the obstacle course](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

邀请几位同学站到**我的电脑**标识下面

利用组织者提供的标识**HOP1，2，3**展示如何通过路由器-到ISP-网站服务器的过程，

讨论在这个演示中，学生代表了什么？数据是如何进行流转的？**HOP1，2，3**的作用是什么，如果没有他们活动是否可以继续下去？

![A photo showing a facilitator explaining the signs](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

10<br>分钟
### 活动分步介绍

开始之前要请几位参与者选择“数据包”这个角色

创建以下场景：

> 表演者打开**我的电脑**，计划去YouTube看电影，在我的电脑转换“youtube”到所有计算机可以读取的代码，然后把该代码为几个互联网的“数据包”开始发送。 该志愿的学生就是这些数据包中的一个。请他们准备开始

![A photo showing the activity in action and a person playing as a local router](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### Hop 1（标识1）: Local Router 本地路由器

请表演数据包的同学走到本地路由器标识下，并解释

> 数据首先是通过路由器或者是调制调节器连接外网的
#### Hop 2: 互联网服务提供商

请学生走到ISP，解释

> 随后一个数据包送过来，到了互联网服务提供商，这是所有的方式发送到YouTube的路由器之一。
#### Hop 3: 公司路由器

> 一旦数据包获得通过YouTube的路由器，它发送到公司总部的计算机，将把需要的我的视频数据告诉youtube。
#### 网站

> youtube在接收到我发出的数据包之后，就会把我需要的视频转换成所有电脑可以观看的文件形式打包原路返回

**要求学生为例走回到你身边，确保在回来的路上每一跳暂停。
#### IP地址

当学生的回来之后 ，询问是否有人知道在每一跳的设备究竟是如何知道从哪里发送一个数据包。 如果没有人知道，请解释：

> 他们使用的IP地址！ 每一台设备或计算机网络或在网上有一个IP（或“互联网协议”）的地址。 这就像一个家庭地址-它可以帮助设备找到彼此沟通。 IP地址有4组数字在这样的字符串：172.168.3.12
#### 在 HOP 之间

为了使超越障碍训练场更有趣，你可以放置跳（两个节点之间的）“间谍”。你可以看一下[EFF](https://www.eff.org/pages/tor-and-https)这个网站是如何解释第三方可能截获节点之间的数据。而你的哪些数据是受保护的，什么是弱势群体，以及向谁学习说话。

---

15<br>分钟
### 看看谁掌握的最好

现在可以让同学们之间组织团队来展示互联网是如何运作的了

**解释，他们都是“包”，由一个同学提出将要前往的网址，其他同学扮演数据包试图用他们的方式前往Google.com（或您所选择的网站）， 他们必须在移动到下一个前的每一“节点”停顿。

**可以在每一个节点之上设计一些有趣的游戏增加难度

![A photo showing learners doing challenges before moving to the next hop](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

当完整的数据包通过调整进入下一个节点，我们可以解释

问数据包以形成单个文件线和移动通过障碍的路线最快的速度!你可以有时间多长时间每个人都要通过的课程，看看谁最快使它的人。

![A photo of the learners building a single line to play the activity](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

10<br>分钟
### 活动反思

毕竟学生已经完成了超越障碍训练场，他们展示的数据包是多么快都能够通过互联网在现实生活中移动

_如果你没有上网，或者是短期时间，跳过Ping实用工具演习。._

一起讨论以下问题

> - 从你的电脑发出请求到获得内容大约需要多少时间？
>   *你认为你的速度快还是网络的速度快？
> -  当你键入一个网址并回车在互联网上会发生什么？ 
> - 什么是互联网的“一部分”？
> - 怎么做才能让大量的信息通过低带宽的网络部分?
> - 什么是互联网和万维网？两者之间的区别在哪里？

Ping是Windows、Unix和Linux系统下的一个命令。ping也属于一个通信协议，是TCP/IP协议的一部分。利用“ping”命令可以检查网络是否连通，可以很好地帮助我们分析和判定网络故障。应用格式：Ping空格IP地址。该命令还可以加许多参数使用，具体是键入Ping按回车即可看到详细说明**具体的方法请google.com**

```
ping 是一个在计算机上的函数，使您可以检查看看您的计算机可以连接到另一台计算机是否畅通，通过向它发送数据 '包' 并看到数据包回来需要多久。
```

![A photo of the learners discussing the activity](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

让学生上机体会 ping 命令

讨论结果

完成 **[活动结束之后的调查表](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Thanks a lot for the translation! Your awesome work is now live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#zh-s
:smile_cat:
