### ISSUE TITLE
Localization of aside.md into Chinese Simplified

### ISSUE THREAD

**Issue by nizibaba** [mozilla/mozilla-club-activity-ping-kong#22]
#### 活动受众
- 8+
- 可以独立思考的受众
#### 活动所需材料
- 打印 [活动课件标识](http://www.mousesquad.org/files/u4/pingkongcards.png)
- Firefox 浏览器
#### 学习目标
- 搜索术语，URL和IP地址之间区分
- 了解两台计算机之间的信息是如何交互的
- 描述Web（网络）和Internet（互联网）之间的实际差别
- 认识 Ping 命令
#### 学习者如何转变成导师
- 培养学生或经验不是很丰富的主持人，这样他们就可以练习领导这项活动
- 如果一些学生在活动中动作更快或更自信，请让他们与另一组同伴进行辅导
- 活动结束之后鼓励学生教他们的朋友和家人。
#### 了解不同社区再创作

Mozilla来自世界各地的志愿者和教育工作者根据这个题材进行了不同的再创作，您可以加入我们的讨论并和帮助我们进行更多的创作 [欢迎加入](https://discourse.webmaker.org/c/curriculum).

**Comment by soapdog** [comment]
Thanks a lot for the translation! Your awesome work is now live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#zh-s
:smile_cat:
