### ISSUE TITLE
Localization of aside.md to Bengali (bd)

### ISSUE THREAD

**Issue by mijanurrahman** [mozilla/mozilla-club-activity-ping-kong#3]
#### শ্রোতৃমণ্ডলী
- ৮ + 
- সিস্টেম চিন্তাবিদদের প্রারম্ভে
#### উপকরণসমূহ
- প্রিন্ট করা [বিধিনিষেধ কোর্স স্বাক্ষর](http://www.mousesquad.org/files/u4/pingkongcards.png)
- ওয়েব ব্রাউজার (ঐচ্ছিক)
#### শিক্ষার উদ্দেশ্য
- সার্চের শর্তাবলী, URL এবং IP ঠিকানা গুলুর মধ্যে প্রভেদ সৃষ্টি করা
- দুটি কম্পিউটারের মধ্যে তথ্যের অবাধ প্রবাহ লক্ষ্য করা
- ওয়েব এবং ইন্টারনেটের মধ্যে প্রয়োগিক পার্থক্য বর্ণনা করা
- ওপেন ওয়েব সরঞ্জাম ব্যাবহার করে সার্ভারের ফিজিক্যাল ঠিকানা নির্ণয় করা।
#### কিভাবে শিক্ষার্থীরা প্রশিক্ষক হয়ে উঠবে
- কোন শিক্ষার্থী বা কম ভিজ্ঞ সহায়তাকারীদের নজরে রাখুন যেন তারা নিজেরা এই কার্যকলাপে নেতৃত্ব দিয়ে অনুশীলন করতে পারে।
- যদি কোন ছাত্র দ্রুত এগিয়ে যায় বা কার্যকলাপে বেশি আত্মবিশ্বাসী হয়, তাদের বলুন অন্য দলকে মেন্টরিং করতে।
- ছাত্রদের এই বলে শেষ করুন যেন তারা এই কার্যকলাপ তাদের বন্ধু বান্ধব ও স্বজনদের শেখায়।
#### কমিউনিটির রিমিক্সসমূহ দেখুন

দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে  [আলোচনা ফোরামে](https://discourse.webmaker.org/c/curriculum)।

**Comment by soapdog** [comment]
Added this to the repository, thanks! :+1: 

Once we have the Bengali version of activity.md we'll move it into the live web version.

**Comment by SubhrajyotiSen** [comment]
@soapdog I'm working on the Bengali translation of activity.md. It will be complete soon

**Comment by soapdog** [comment]
Awesome news! :+1: keep us posted!
