### ISSUE TITLE
Localization of activity.md into Indonesian

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-ping-kong#4]
---

title: Ping Kong
github: mozilla/mozilla-club-activity-ping-kong
image: pingkong.png
competencies:
    - {label: "Web Mechanics", type: "web-mechanics"}
### Ping Kong

Dibuat oleh [MOUSE ](http://mouse.org/) termasuk foto, Chad Sansing, dan remix untuk Klub berdasarkan [Mozilla](https://webmaker.org/mentor).

Bagi banyak orang, "Internet" adalah sebuah konsep abstrak dan luar biasa . Kegiatan ini menantang peserta didik untuk berpikir secara konkret **tentang bagaimana internet berkomunikasi dengan komputer.**

1-2 Jam
### Persiapan

**Lengkapi** [Survey Sebelum Kegiatan](http://goo.gl/forms/Uua6yKIy5E).

Selanjutnya **Melakukan aktifitas sendiri** Agar menjadi lebih familiar.

**Membiasakan diri anda** dengan [Istilah-istilah] Berikut (https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. Perintah Baris **Command line/Command Prompt**
2. **Hop**
3. Alamat Protokol Internet / **Internet Internet Protocol (IP) Address**
4. **Internet Service Provider (ISP)**
5. Web Server
6. Local Area Network (LAN)
7. Packet
8. Ping
9. Router
10. Traceroute

**Cetak dan Gunting** [Tanda rintangan Ping Kong](http://www.mousesquad.org/files/u4/pingkongcards.png).

**Sediakan cukup ruang** dalam kelas untuk “rintangan.” **Tutup kartu** yang berlabel “Komputer Saya” dan “Website” disisi berlawanan dalam ruangan.!

[Kartu Ping Kong](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

10<br>Menit
### Pengantar

Bertanya kepada peserta didik, _“Bagaimana anda terhubung ke internet?”_

Ambil beberapa ide dari kelompok, kemudian jelaskan gambar berikut ini:
![gambar internet](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)  

> "Internet" adalah sistem jaringan dan "Web" berada di atas Internet dan menyediakan sebuah antarmuka untuk melihat dan berinteraksi dengan informasi yang tersimpan di berbagai komputer di seluruh dunia. Artikel ini singkat dari Skillcrush detail menjelaskan perbedaan antara Internet dan Web
> Lanjut menjelaskan
> Setiap kali Anda meminta Internet untuk melakukan sesuatu, apakah dengan memasukkan URL ke dalam browser atau menonton video di youtube, anda melakukan permintaan "hop internet. "melalui beberapa perangkat jaringan, seperti router dan switch dan server, dalam perjalanannya dari komputer Anda ke server website

Menonton video pengantar untuk memberikan siswa sedikit lebih konteks sebelum memulai rintangan:
#### Dari sana dan kembali lagi: Kisah Sebuah Paket

[![Dari sana dan kembali lagi: Kisah Sebuah Paket](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

15<br>Menit
### Menunjukan Jaringan

Membentuk kelompok improvisasi kecil 4-5 aktor. Berkumpul dan bertukar pikiran cara untuk melakukan bagaimana Internet bekerja. Pikirkan tentang bagaimana menggunakan ruangan anda - Anda dapat melakukan di mana saja di ruang di sekitar Anda dan menyebar dan bergerak sebanyak yang Anda inginkan. Pikirkan tentang bahan di sekitar Anda dan ambil setiap alat peraga yang dapat membantu Anda menunjukkan jaringan bekerja..

Lakukan sandiwara satu dengan yang lain. Berikan penghargaan untuk setiap kelompok. tertawa dan bersorak khususnya untuk setiap kejadian hebat yang terjadi saat pertunjukan jaringan !

---

5<br>Menit
### Mengatur kendala perjalanan

Katakanlah bahwa untuk membantu memahami jalan ini, kita akan **melakukan ping/traceroute manusia dalam tantangan**

Kita akan melakukan perjalanan dari i) Komputer Lokal melalui ii) a LAN ke iii) Internet untuk mendapatakan iv) Google.com atau situs pilihan anda.!
![gambar](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

Mintalah kelompok untuk **mengumpulkan tanda "Komputer saya" sign** dan mintalah **tiga relawan.**

Tangan dari tiga relawan diberi label  **"Hop 1: Router Lokal," "Hop 2: Penyedia layanan Internet dan "Hop 3: Router Website Perusahaan"** dan meminta mereka untuk menyebar ke seluruh ruangan.

Jelaskan bahwa **Setiap tanda mewaliki "hop" yang berbeda** yang setiap permintaan internet harus melaluinya sebelum  sampai ke website yang di cari oleh pengguna. **sisa dari siswa**  adalah paket kode komputer yang mencoba untuk mendapatkan situs web di ujung ruangan.!

![gambar](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

10<br>menit
### Model Kendala Perjalanan

**Pilih salah satu siswa untuk bertindak sebagai model "paket" dari** sisa kelompok sebelum mereka semua memulai aktivitas.

Berikan skenario berikut kepada peserta didik

> Saya berada didepan komputer saya dan saya memutuskan untuk menonton video di YouTube. Setelah saya ketik alamat web, komputer saya mengubah 'youtube.com' menjadi kode yang semua komputer dapat membacanya dan kemudian membagi kode yang menjadi beberapa "paket" internet. siswa relawan ini merupakan salah satu paket!

![Gambar](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### Hop 1: Router Lokal

Mintalah contoh siswa untuk berjalan menuju “Hop 1: Router Lokal” dan jelaskan:

> Pertama paket akan hop melalui perangkat jaringan lokal seperti router, switch atau modem di gedung Anda. Perangkat jaringan lokal kemudian mengirim paket ke Internet.
#### Hop 2: Penyedia Layanan Internet

Buat siswa berjalan dan jelaskan sampai ke hop berikutnya:

> Setelah paket tiba di sini, ke penyedia layanan Internet, ini akan di terkirim semua salah satunya ke router YouTube.
#### Hop 3: Router Perusahaan

> Setelah paket sampai ke router youtube, paket tersebut di kirimkan ke komputer pusat perusahaan yang akan menstreaming video saya.
#### Website

> Untuk mendapatkan video streaming di komputer saya, komputer YouTube mengkonversi video saya ke dalam paket juga, agar melakukan perjalanan sepanjang jalan kembali ke komputer saya di jalan yang sama dari perangkat jaringan yang dibutuhkan untuk sampai ke YouTube.

**mintalah contoh siswa berjalan kembali kepada Anda,** astikan untuk berhenti di setiap hop dalam perjalanan kembali.
#### Alamat IP

Ketika siswa kembali, tanyakan apakah ada yang tahu bagaimana perangkat pada setiap hop tahu persis di mana untuk mengirim paket. Jika tidak ada yang tahu, Jelaskan:

> Mereka menggunakan alamat IP! Setiap perangkat atau komputer dalam jaringan atau online memiliki alamat IP (atau "Protokol Internet"). Ini seperti alamat rumah - dan membantu perangkat menemukan satu sama lain dan berkomunikasi. Alamat IP memiliki 4 set angka dalam string seperti ini: 172.168.3.12
#### Diantara Hop

Untuk membuat rintangan lebih menarik, Anda mungkin menempatkan "mata-mata pemerintah" antara hop. [Sumber daya ini dari EFF](https://www.eff.org/pages/tor-and-https) jelaskan bagaimana pihak ketiga memungkinkan mencegat data antara hop. Berbicara dengan peserta didik tentang data apa dilindungi, apa yang rentan, dan kepada siapa.

---

15<br>Menit
### Akhir dari Balapan!

Sekarang saatnya bagi setiap orang untuk mencoba rintangan!

*_Jelaskan kepada siswa bahwa semua "paket" mereka  *_ mencoba untuk membuat jalan mereka ke Google.com (atau website pilihan anda) untuk menyelesaikan permintaan Internet seseorang. Mereka harus berhenti di setiap "hop" sebelum pindah ke berikutnya.

**Tapi tunggu, Ada pusaran!** Sebelum paket bisa sampai dari satu hop ke hop berikutnya, mereka harus menyelesaikan tantangan cepat yang ditimbulkan oleh akting siswa sebagai Hop. _Contoh: Lakukan 5 kali Lompatan bintang ! Bernyanyi “Selamat Ulang tahun” dan lain lain._

![Gambar](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

Ketika paket melengkapi tantangan Hop, para Hop akan memungkinkan paket untuk memindahkan lokasi berikutnya sampai paket mencapai "Website".

Mintalah paket untuk membentuk satu baris-file dan bergerak melalui rintangan secepat mereka bisa! Anda dapat menghitung waktu seseorang berapa lama waktu yang dibutuhkan setiap orang untuk mendapatkan melalui arah ini agar mengetahui siapa yang paling tercepat.!
![Gambar](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

10<br>Menit
### Refleksi

Setelah semua peserta telah selesai menyelesaikan rintangan, tunjukan kepada mereka betapa cepat paket dapat bergerak melalui internet dalam kehidupan nyata.
- Jika Anda tidak memiliki konektivitas internet atau sedang kekurangan waktu, melewatkan ping Utilitas latihan *seperti:.?

Mintalah kelompok beberapa pertanyaan reflektif

```
* Berapa lama waktu yang Anda butuhkan untuk mendapatkan semua jalur dari komputer melalui Internet ke website
* Apakah Anda berpikir komputer bergerak lebih cepat melalui Internet daripada yang Anda lakukan?
* Apa yang terjadi di Internet ketika Anda mengetik alamat Web dan tekan enter?
* Apa 'bagian' dari internet?
* Bagaimana sejumlah besar informasi melalui bagian bandwidth yang rendah dari Jaringan ?
* Apa bedanya antara Internet dan World Wide Web?
```

Ambil beberapa tebakan dan kemudian jelaskan bahwa kita benar-benar bisa tahu persis berapa lama permintaan nyata dengan menggunakan utilitas Ping di Command Prompt (PC) atau Terminal (Mac). Atau jika Anda sedang offline, hanya menjelaskan apa yang akan terjadi.

```
Ping adalah fungsi pada komputer yang memungkinkan Anda memeriksa untuk melihat apakah komputer Anda dapat terhubung ke komputer lain melalui jaringan atau online dengan mengirimkan 'paket' data untuk itu dan melihat bagaimana lama waktu yang dibutuhkan untuk paket untuk kembali.!
```

![gambar](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

Mintalah siswa untuk menebak berapa lama waktu yang dibutuhkan untuk 5 paket ping ke Google dan kembali. Tuliskan tebakan mereka di dinding.

Entah dalam kelompok (jika peralatan tersedia) atau sebagai satu kelompok melihat proyektor, jalankan utilitas ping di google.com (menggunakan lembar tip untuk petunjuk!).

Diskusikan hasilnya.

Lengkapi **[Survey setelah kegiatan](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Your translation is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#id

:smile_cat: thanks a lot for your support, we appreciate it a lot! :smiley_cat:
