### ISSUE TITLE
Localization of aside.md into Indonesian

### ISSUE THREAD

**Issue by harlyumboh** [mozilla/mozilla-club-activity-ping-kong#5]
#### Peserta
- 8+
- Pemikir Sistem Pemula
#### Bahan
- Cetakan [Tanda Arah tantangan](http://www.mousesquad.org/files/u4/pingkongcards.png)
- Web browser (optional)
#### Tujuan Pembelajaran
- Bedakan antara istilah pencarian, URL dan alamat IP
- Ikuti arus informasi antara dua komputer
- Jelaskan perbedaan praktis antara web dan Internet
- Cari alamat fisik server menggunakan alat pada Open Web.
#### Bagaimana peserta didik menjadi mentor
- Seorang siswa atau fasilitator yang kurang berpengalaman sehingga mereka dapat berlatih terlebih dahulu pada kegiatan ini..
- Jika beberapa siswa belajar lebih cepat atau lebih percaya diri dalam kegiatan ini, meminta mereka untuk melihat mentor kelompok lain.
- Akhiri dengan mendorong siswa untuk mengajarkan kegiatan ini kepada teman dan keluarga mereka.
#### Lihat remix komunitas

Periksa cara pendidik dan aktivis lain yang telah dimodifikasi kegiatan ini untuk peserta mereka yang lebih spesifik di [Discussion Forum](https://discourse.webmaker.org/c/curriculum) kami.

**Comment by soapdog** [comment]
Your translation is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#id

:smile_cat: thanks a lot for your support, we appreciate it a lot! :smiley_cat:

**Comment by harlyumboh** [comment]
your welcome, thanks so much
