### ISSUE TITLE
Localization of activity.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-ping-kong#7]
---

title: Ping Kong
github: mozilla/mozilla-club-activity-ping-kong
image: pingkong.png
competencies:
    - {label: "Web Mechanics", type: "web-mechanics"}
### Ping Kong

Produziert von [MOUSE](http://mouse.org/) inklusive Fotos, Chad Sansing und remixed für Clubs von [Mozilla](https://webmaker.org/mentor).

Für viele ist "das Internet" ein abstraktes und unüberschaubares Konzept. Diese Aktivität fordert Lernende heraus, **konkret darüber nachzudenken, wie das Internet mit einem Computer kommunziert.**

1-2 Stunden
### Vorbereitung

**Beantworte den** [Vorbereitungs-Fragebogen](http://goo.gl/forms/Uua6yKIy5E).

Danach **absolviere die Übung selber**, um dich damit vertraut zu machen.

**Werd vertraut** mit den folgenden [Begriffen](https://github.com/mozilla/webmaker-curriculum/wiki/Glossary):
1. Kommandozeile/-Prompt
2. Hop
3. Internet-Protokoll-Adrese (IP-Adrese)
4. Internet-Anbieter (Internet Service Provider, ISP)
5. Web-Server
6. Local Area Network (LAN)
7. Paket
8. Ping
9. Router
10. Traceroute

**Erstelle dir einen Ausdruck** von den [Ping Kong Hindernislauf-Zeichen](http://www.mousesquad.org/files/u4/pingkongcards.png) und **schneide sie aus**.

**Schaffe ausreichend Platz** in deinem Raum für einen “Hindernislauf.” **Hänge die Karten** mit den Beschriftungen “Mein Computer” und “Die Website” an entgegengesetzten Seiten des Raumes auf.

![Ping Kong Karten](http://www.mousesquad.org/files/u4/pingkongcards.png)

---

10<br>min
### Einführung

Frag die Lernenden, _“Wie gehst du in's Internet?”_

Sammle die Ideen aus der Gruppe und erkläre dann Folgendes:

![Internet-Grafik](http://4b93n32qwvjj3ddn5w3yhffoas6.wpengine.netdna-cdn.com/wp-content/uploads/2013/03/internetvstheweb.jpg)

> Das "Internet" ist ein System aus Netzwerken und das "Web" sitzt da drauf und bietet eine Schnittstelle zum Betrachten und Interagieren mit Informationen an, die auf verschiedenen Computern überall in der Welt gelagert sind. Dieser kurze Artikel von Skillcrush erklärt den Unterschied zwischen Internet und Web genauer.

Dann erkläre, dass:

> Jedes Mal, wenn du das Internet um etwas bittest, sei es durch die Eingabe einer URL im Browser oder das Ansehen eines YouTube-Videos, fordert dein Internet "Hops" über mehrere Netzwerk-Geräte wie Router, Switches und Server an, um den Weg von deinem Computer zum Server der Website zu finden.

Seht euch das Einführungsvideo gemeinsam an, um den Lernenden etwas mehr Kontext zu geben, bevor der Hindernislauf beginnt:
#### Hin und zurück: Die Geschichte eines Paketes

[![Hin und zurück: Die Geschichte eines Paketes](http://img.youtube.com/vi/WwyJGzZmBe8/0.jpg)](http://www.youtube.com/watch?v=WwyJGzZmBe8)

---

15<br>min
### Das Netz nachstellen

Bildet kleine Gruppe von 4-5 Schauspielern. Überlegt euch zusammen einen Weg, die Funktionsweise des Internet nachzustellen. Denkt darüber nach, wie ihr den Raum nutzt - ihr könnt jede freie Fläche nutzen und soviel umherwandern, wie ihr wollt. Betrachtet das Material um euch herum und schnappt euch alles, was dabei helfen könnte zu zeigen, wie das Netz funktioniert.

Spielt es euch dann einander vor. Applaudiert einander. Insbesondere lacht und lobt besonders tolle Momente beim Nachstellen der Geschichte des Netzes!

---

5<br>min
### Den Hindernislauf aufbauen

Erkläre, dass ihr jetzt zum Verstehen des Pfades, **einen menschlichen Ping/eine menschliche Traceroute in einem Hindernislauf spielen** werdet.

Wir werden von einem i) lokalen Rechner über ii) LAN zum iii) Internet wandern, um iv) Google.com oder eine Website eurer Wahl zu erreichen.

![Bild](https://farm9.staticflickr.com/8066/8232365693_d79ddb19f7_b.jpg)

Bitte die Gruppe, sich **unter dem Schild "Mein Computer" zu sammeln** und frage nach **drei Freiwilligen.**

Gib ihnen die Schilder mit der Aufschrift **"Hop 1: Lokaler Router," "Hop 2: Internet-Anbieter" und "Hop 3: Der Router der Website"** und bitte sie, sich im Raum zu verteilen.

Erkläre, dass die **Zeichen für verschiedene "Hops" stehen**, die eine Internet-Anfrage durchqueren muss, bevor sie zu der Website gelangt, die der Nutzer aufsuchen möchte. Die **anderen Schüler** stellen Pakete aus Computer-Code dar und versuchen, an das andere Ende des Raumes zu gelangen.

![Bild](https://farm9.staticflickr.com/8350/8232367115_3662ebf154_b.jpg)

---

10<br>min
### Modelliere den Hindernislauf

**Wähle einen dieser “Paket”-Schüler als Modell** für den Rest der Gruppe, bevor die Aktivität beginnt.

Stelle den Lernenden folgendes Szenario vor

> Ich sitze an meinem Rechner und möchte ein Video auf YouTube anschauen. Nachdem ich die Web-Adresse eingegeben habe, wandelt mein Computer ‘youtube.com’ in Code um, den alle Rechner verstehen können und teilt diesen Code dann in mehrere Internet-“Pakete” auf. Dieser Schüler hier repräsentiert eines der Pakete.

![Bild](https://farm9.staticflickr.com/8481/8233430584_ce59b4a546_b.jpg)
#### Hop 1: Lokaler Router

Bitte den Schüler, zum “Hop 1: Lokaler Router” zu gehen und erkläre:

> Als erstes wandert das Paket zu lokalen Netzwerk-Geräten wie Router, Switches oder Modems im Gebäude. Dieses Gerät sendet das Paket dann in's Internet.
#### Hop 2: Internet-Anbieter

Lass den Schüler zum nächsten Hop gehen und erkläre:

> Nachdem ein Paket hier beim Internet-Anbieter (oder Internet Service Provider, kurz ISP) angelangt ist, wird es direkt zu einem von YouTubes Routern geschickt.
#### Hop 3: Firmen-Router

> Nachdem ein Paket bei einem von YouTubes Routern angelangt ist, wird es an das Hauptquartier der Firma weitergeleitet, die das Streamen des Videos startet.
#### Website

> Um das Video auf meinem Computer zu streamen, wandelt der Rechner von YouTube das Video auch in Pakete um, die den ganzen Weg zurück über die Netzwerkgeräte nehmen, auf die sie auch hingelangt sind.

**Bitte den Schüler, zu dir zurückzukommen,** und dabei an jedem Hop kurz anzuhalten.
#### IP-Adresse

Nachdem der Schüler angekommen ist, frag in die Runde, ob irgendjemand weiß, woher ein Gerät an jedem Hop genau weiß, wohin es ein Paket senden muss. Falls es niemand weiß, erkläre:

> Sie benutzen IP-Adressen! Jedes Gerät und jeder Computer im Netzwerk oder online hat eine IP-Adresse (oder “Internet Protocol”-Adresse). Es ist wie eine Anschrift - es hilft den Geräten dabei, sich zu finden und miteinander zu reden. IP-Adresse bestehen aus 4 Gruppe von Nummern in einer Zeichenkette wie: 172.168.3.12
#### Zwischen Hops

Um den Hindernislauf interessanter zu gestalten, kannst du "Spione der Regierung" zwischen Hops platzieren. [Diese Seite von EFF](https://www.eff.org/pages/tor-and-https) erklärt, wie Dritte Daten zwischen Hops abgreifen können. Sprich mit den Lernenden darüber, welche Daten geschützt und welche für wen verwundbar sind.

---

15<br>min
### Lass den Lauf beginnen!

Jetzt ist es an der Zeit, jeden den Hindernislauf ausprobieren zu lassen!

**Erkläre den Schülern, dass sie alle “Pakete” sind**, die auf den Weg zu Google.com (oder einer anderen Website ihrer Wahl) unterwegs sind, um die Internet-Anfrage von jemandem zu erfüllen. Sie müssen an jedem “Hop” inne halten, bevor sie weitergehen können.

**Aber halt, da gibt es noch eine Sache!** Bevor ein Paket von einem Hop zum nächsten kann, müssen sie eine kurze Herausforderung absolvieren, die von dem Schüler, der den Hop spielt, gestellt wird. _Beispielsweise: Mach 5 Hampelmänner! Singe “Happy Birthday” usw._

![Bild](https://farm9.staticflickr.com/8342/8233430386_45a5aba09a_b.jpg)

Sobald ein Paket die Herausforderung eines Hops gelöst hat, erlaubt der Hop dem Paket zur nächsten Station weiterzuwandern, bis das Paket "Die Website" erreicht hat.

Bitte die Pakete, eine Einzeldatei-Linie zu bilden und so schnell wie möglich durch den Hindernislauf zu wandern! Jemand kann die Zeit stoppen, um zu sehen, wer es am schnellsten durch geschafft hat.

![Bild](https://farm9.staticflickr.com/8207/8233430120_ea0c7fc7fa_b.jpg)

---

10<br>min
### Reflexion

Nachdem alle Lernenden den Hindernislauf absolviert haben, zeig ihnen, wie schnell Pakete sich im echten Internet bewegen.

_Falls du keine Internet-Verbindung hast oder die Zeit knapp wird, überspring die Ping-Werkzeug-Übung._

Bitte die Gruppe, über die folgenden Fragen nachzudenken:

```
* Wie lange hast du gebraucht, um vom Computer über das Internet bis zur Website zu gelangen?
* Glaubst du, ein Computer bewegt sich schneller durch das Internet als du?
* Was passiert im Internet, wenn du eine Web-Adresse eingibst und auf Enter drückst?
* Aus welchen 'Teilen' besteht das Internet?
* Wie schaffen es große Mengen von Informationen durch Abschnitte mit geringer Bandbreite im Netz?
* Worin besteht der Unterschied zwischen dem Internet und dem World Wide Web?
```

Sammle ein paar Antworten und erläutere dann, dass wir tatsächlich genau feststellen können, wie lange eine Anfrage benötigt, indem wir das Ping-Werkzeug auf der Kommandozeile oder dem Terminal verwenden. Falls du offline bist, erkläre, was dabei passieren würde.

```
Ping ist eine Funktion, mit der du auf deinem Computer prüfen kannst, ob er sich mit einem anderen Rechner im Netzwerk oder online verbinden kann, indem du ein ‘Paket’ aus Daten hinschickst und misst, wie lange es dauert, bis es zurückgekommen ist.
```

![Bild](https://farm9.staticflickr.com/8484/8233431352_d817e553fa_b.jpg)

Bitte die Schüler, konkrete Schätzungen abzugeben, wie lange 5 Pakete zu Google und zurück benötigen werden. Schreib diese auf einen Zettel.

Verfolgt entweder in Gruppe oder gemeinsam (je nach Verfügbarkeit an Ausrüstung) an einem Beamer, wie ein Ping zu google.com abläuft (auf dem Hinweisblatt stehen die Anweisungen!).

Diskutiert die Ergebnisse.

Beantwortet dann den **[Nachbereitungs-Fragebogen](http://goo.gl/forms/ezm6IXWhhM)**.

**Comment by soapdog** [comment]
Thanks a lot for your hard work! :smile_cat: 

Your translation is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#de
