### ISSUE TITLE
Localization of aside.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-ping-kong#8]
#### Publikum
- 8+
- Beginner im systematischen Denken
#### Material
- Ausgedruckte [Hindernislauf-Zeichen](http://www.mousesquad.org/files/u4/pingkongcards.png)
- Web-Browser (optional)
#### Lernziele
- Unterscheiden zwischen Suchbegriffen, URLs und IP-Adressen
- Den Fluss von Informationen zwischen zwei Computern verfolgen
- Die praktischen Unterschiede zwischen dem Web und dem Internet beschreiben
- Die physische Adresse von Servern mit Werkzeugen im Offenen Web bestimmen
#### Wie Lernende zu Mentoren werden
- Begleite einen Schüler oder einen wenig erfahrenen Moderator, so dass sie das Leiten dieser Aktivität üben können.
- Falls einige Schüler schneller oder sicherer bei dieser Aktivität sind, bitte sie, eine andere Gruppe mit zu betreuen.
- Schließe mit der Aufforderung an die Schülere, ihren Freunden und Familienangehörigen diese Aktivität auch beizubringen.
#### Weitere Community Remixes

Siehe auch weitere Wege in unserem [Diskussions-Forum](https://discourse.webmaker.org/c/curriculum), wie Lehrende und Aktivisten diese Aktivität für ihr Publikum abgewandelt haben.

**Comment by soapdog** [comment]
Thanks a lot for your hard work! :smile_cat: 

Your translation is live at http://mozilla.github.io/mozilla-club-activity-ping-kong/#de
