### ISSUE TITLE
Improvements on accessibility and consistency

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-ping-kong#9]
I noticed several inconsistencies and bad a11y while translating this files.
- Inconsistent usage of quotation marks (single quotes: ', double quotes: " and quotation marks: “ ” mixed)
- Inconsistency on spaces after pounds (which are mapped to headings level) - I prefer a space after the pound #
- "Ping is a function on computers that lets you check to see if your computer can connect to another computer over the network or online by sending a ‘packet’ of data to it and seeing how long it takes for the packet to come back." in a blockquote (on purpose?)
- alt-text for images are just "Image" - imagine what you would want to read if that resource couldn't be loaded (say, Flickr faces a DDoS) and put **that** into the alt text!

Nevertheless I lend to the English original.

**Comment by soapdog** [comment]
Thanks a lot for pointing them out.

The bullet point related to the # sign used for headings doesn't affect a11y because those files are processed before turning into HTML. The screen readers will not pick those. I too prefer them with a space after the # sign.

The other items on your list are real and I will try to fix them.

**Comment by soapdog** [comment]
Fixed the alt-text and quotes used in the English locale. Can you double check that and give me some feedback?

**Comment by Ryuno-Ki** [comment]
Will do. Sorry, I was ill/busy the last days.

**Comment by Ryuno-Ki** [comment]
It looks better now (can tell for sure once I fixed that permission error preventing me to fire up Orca screenreader), but I assume, the [AT](https://en.wikipedia.org/wiki/Assistive_technology) will already tell, that there is an image with alt text. However, this way, you care for people with flaky internet (where the image maybe couldn't be downloaded or is anyhow broken). Leave it this way.

I won't find time to submit an updated German translation until end of the year. I assume, that is fine, because those are merely editorial changes …
